### ISSUE TITLE
Dead Webpages for imx-8x-ssk development kit

### ISSUE THREAD

**Issue by ghost** [ArrowElectronics/Security-Starter-Kits#5]
Arrow continues to sell the dev kit, but has stopped supporting the product by removing support webpages.

Not helpful. Makes me question whether I would ever want to purchase another Arrow dev kit.

**Comment by ghost** [comment]
The support pages are back up. Seems they were only offline temporarily.

**Comment by W-Dragon-Jr** [comment]
Sorry for the inconvenience, but glad to hear things are back up.
